project:
  type: website
  output-dir: docs

website:
  title: "asdfjkdajsklfdf"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: whoami

format:
  html:
    theme: dark
    css: styles.css
    toc: true



